### PR TITLE
Basic Layout

### PR DESCRIPTION
**Pull request by rmcgregor1990**
Basic repo layout:
- Python package for lark language server using `pygls`
- Vscode client extension
- Basic development guide using vscode

### CODE REVIEW

**Comment by MegaIng** [comment]
What is the `.vscode` folder?

I think for what we write in `setup.py` we should have more discussion somewhere else, but looks good for a first draft.

**Comment by rmcgregor1990** [comment]
`.vscode` contains all the VSCode config for this folder/project. Its design is a little weird as there is some user specific config files in there like `config.json` and some project level config files in there like `tasks.json` or `launch.json`.

`config.json` is user config and is in `.gitignore`
`tasks.json` defines runable "tasks" from within vscode, these can just be shell commands. The task for compiling the vscode typescript client is in there at the moment.
`launch.json` defines debugger configuration for launching targets. It currently contains the config for launching the python server and the vscode extention client. Which makes for quite a nice development environment.

**Comment by MegaIng** [comment]
I am not completely sure if we should add that folder, since it is very IDE specific, but it is clearly marked, so fine. Do we want to wait for more voices, or just merge this? (btw, can you merge?)

**Comment by rmcgregor1990** [comment]
I see what you're saying, but its quite helpful to have an editor to develop a language server against and vscode is basically the reference implementation. Also yeah it doesn't hurt anyone to have it there.

I can merge. But I would rather wait for a bit more input, I don't want the project structure to be completely different to what someone was expecting.

Plus there are some other things I would like to get working, namely an example test and some CI. Thought that could be done separately.

**Comment by erezsh** [comment]
> Provides a language server for the Lark grammar

I think what we actually want is a generic language server for *any* language that is defined by a `.lark` grammar file.

We can then create a folder, say `examples/lark_grammar`, that will use the server specifically to provide an implementation for editing Lark grammars, by giving it `lark.lark` and extra code.

It's a little confusing, but I hope I made myself clear.

**Comment by rmcgregor1990** [comment]
> > Provides a language server for the Lark grammar
> 
> I think what we actually want is a generic language server for _any_ language that is defined by a `.lark` grammar file.
> 
> We can then create a folder, say `examples/lark_grammar`, that will use the server specifically to provide an implementation for editing Lark grammars, by giving it `lark.lark` and extra code.
> 
> It's a little confusing, but I hope I made myself clear.

Fair enough, I guess I thought we were starting with a lark grammar specific language server and then trying to extract as much generic functionality once we had an a good idea of what was involved.

**Comment by rmcgregor1990** [comment]
Ok I've added some basic CI for linting and running tests. Does anyone have any further feedback?

**Comment by erezsh** [comment]
> Fair enough, I guess I thought we were starting with a lark grammar specific language server and then trying to extract as much generic functionality once we had an a good idea of what was involved.

Yes, absolutely. I think that's what we're still doing. But since the ultimate goal is to reach a generic solution, I think it's a good idea to have it reflected in the structure, as it would be harder to change later.

But we can leave a lot of placeholders, and focus on getting `lark.lark` to work. We'll slowly grow the generic space as we go along, carried by the specific example.

But if we mix the specific with the generic space, it will be hard to separate later on, and we might get bogged down in foggy design.

I don't want to dictate anything, but I really believe that's the best route to take, so hopefully you can trust me on this.

**Comment by omega16** [comment]
I think its a good thing to have separated the editor part, in vim you have to choose a client plugin for lsp and in the one I'm using you just need to put on your **.vimrc** something like : 

```vim
let g:languageClient_ServerCommands = {
  \  'lark' :  ['comand' ,  'to start',  'the server', 'or ip of', ' tcp server'],
  \ 'python' : ['lsp'],
  \ 'haskell'  :  . . .
\  }
```

I'm still figuring out how to init pygls from there, but right now it seems to work if you start the tcp server by your own and just put the ip. I will use this commit code to start the vim language client testing, so , thanks for the code!

What do the `trigger_characters=[',']` does? I have seen many examples that use it but I can't find it in doc or code and to me it looks like `the "," character would trigger completion request ` and at the same time as part of `options` it sounds like something I would configure client to do.

**Comment by rmcgregor1990** [comment]
> What do the `trigger_characters=[',']` does? I have seen many examples that use it but I can't find it in doc or code and to me it looks like `the "," character would trigger completion request ` and at the same time as part of `options` it sounds like something I would configure client to do.


Heres the description from the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/):
```typescript
/**
* Most tools trigger completion request automatically without explicitly requesting
* it using a keyboard shortcut (e.g. Ctrl+Space). Typically they do so when the user
* starts to type an identifier. For example if the user types `c` in a JavaScript file
* code complete will automatically pop up present `console` besides others as a
* completion item. Characters that make up identifiers don't need to be listed here.
*
* If code complete should automatically be trigger on characters not being valid inside
* an identifier (for example `.` in JavaScript) list them in `triggerCharacters`.
*/
triggerCharacters?: string[];
```

It's basically other characters outside alphanumeric identifiers which should trigger the client to send a completion request to the server. It's asynchronous config sent from server to client.

Its not really required for our uses here, its presence in the code is just a copy paste error on my part.

Hope that clears things up,
Rob

**Comment by erezsh** [comment]
@rmcgregor1990 Does the `.vscode` folder have to be in root? Is there a reason why we shouldn't move it to `editors/vscode`?

Everything else looks fine to me.

**Comment by rmcgregor1990** [comment]
`.vscode` is basically equivalent to an IDE workspace file. Its not related to the vscode LS client extension in `editors/vscode`. Vscode could conceivably be used to launch and debug the language server for other editors as well.
Having it there allows anyone to open the repo root in vscode and easily launch a client/server/both under its builtin debugger. 
Vscode wouldn't pick it up in a nested folder.

It's there to help anyone get up and running with development project quickly. Its a pretty common thing to commit to the root of the project even if only some team members actually use vscode is my experience.
As I see it there are only 2 options:
- leave it committed as is
- remove it and move the contents + instructions into the README.md so people can recreate configuration locally.

**Comment by erezsh** [comment]
Okay. Well, I think we can just merge that in, as far as I'm concerned.

**Pull request merged**
