### PR TITLE
WIP: Error reporting

### PR DESCRIPTION
**Pull request by rmcgregor1990**
This branch is based of #1 , which should be merged first.

This is my first attempt at getting some basic syntax error diagnostics working for `.lark` files.

### CODE REVIEW

**Comment by rmcgregor1990** [comment]
I'm running against the current master of `lark` & hitting an AttributeError when using the `on_error` callback. Seems the error_puppet attribute is `None`:

```
Traceback (most recent call last):
  File "c:\users\magni\projects\lark\lark\lexer.py", line 416, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "c:\users\magni\projects\lark\lark\lexer.py", line 200, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for '8' at line 1 col 1

89897

^

Expecting: {'RULE', '_NL', '__ANON_1', '__ANON_3', 'TOKEN', '__ANON_2'}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\magni\projects\lark\lark\lark.py", line 438, in parse
    return self.parser.parse(text, start=start)
  File "c:\users\magni\projects\lark\lark\parser_frontends.py", line 141, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "c:\users\magni\projects\lark\lark\parser_frontends.py", line 58, in _parse
    return self.parser.parse(input, start, *args)
  File "c:\users\magni\projects\lark\lark\parsers\lalr_parser.py", line 36, in parse
    return self.parser.parse(*args)
  File "c:\users\magni\projects\lark\lark\parsers\lalr_parser.py", line 87, in parse
    for token in stream:
  File "c:\users\magni\projects\lark\lark\lexer.py", line 431, in lex
    raise UnexpectedToken(t, e.allowed, state=e.state)
lark.exceptions.UnexpectedToken: Unexpected token Token('NUMBER', '89897') at line 1, column 1.
Expected one of: 
	* RULE
	* _NL
	* __ANON_1
	* __ANON_3
	* TOKEN
	* __ANON_2


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\magni\projects\lark-language-server\lark_language_server\error_reporting.py", line 22, in get_diagnostics
    lark_grammar_parser.parse(doctext, on_error=on_error)
  File "c:\users\magni\projects\lark\lark\lark.py", line 447, in parse
    return e.puppet.resume_parse()
AttributeError: 'NoneType' object has no attribute `'resume_parse'`
```
Anyone got any advice?

**Comment by erezsh** [comment]
You've run into a limitation in the `on_error` mechanism that we're planning to fix. In the current design, errors that are raised in the lexer (rather than the parser) don't have access to the parser state, and cannot create a puppet.

We already discussed it, and have several ideas in the making.

@MegaIng Iirc you proposed to tackle this. Any progress, or should I go ahead and do it so it doesn't block?

**Comment by erezsh** [comment]
Just a quick update. I'm now in the process of refactoring Lark to solve this issue, so it's possible that it will be solved pretty soon.

**Comment by erezsh** [comment]
Another update: This is now working in branch `resumable`!

(https://github.com/lark-parser/lark/tree/resumable)

**Comment by rmcgregor1990** [comment]
Awesome, I'll give it a try this evening 👍

**Comment by rmcgregor1990** [comment]
Seems to work great!
lark-syntax-errors

**Comment by erezsh** [comment]
Cool, looks like a great start!

**Comment by erezsh** [comment]
Quick update: This should now work with Lark's `master` branch. (`resumable` as been merged)

**Comment by ThatXliner** [comment]
> Seems to work great!
> 
> lark-syntax-errors
> 
> 

I think we should catch some errors and make the messages more user-friendly. Only the raw parsing errors should be made as a last resort.

**Comment by erezsh** [comment]
I'm already working on that. I'm going to use `match_examples` with Lark's own message errors.

**Pull request merged**
